name: local-rag-system
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - fastapi             # 建立API的框架
      - uvicorn[standard]   # 用于运行FastAPI应用的ASGI服务器
      - python-dotenv       # 用于加载 .env 文件
      - pydantic            # 用于数据验证和设置管理
      - pydantic-settings   # 用于管理应用设置
      - python-multipart    # 用于处理文件上传
      - langchain           # 用于构建RAG系统的核心库
      - langchain-community # 包含社区贡献的工具和功能
      - langchain-openai    # 用于与OpenAI API交互
      - qdrant-client       # 用于与Qdrant向量数据库交互
      - pypdf               # 用于处理PDF文件
      - langchain-text-splitters # 用于文本分割
      - langchain-qdrant   # 用于将文档存储到Qdrant数据库中
