name: DeepSeek Config
version: 0.0.1
schema: v1

models:
  - name: DeepSeek
    provider: openai
    model: deepseek-v4-flash
    apiKey: sk-595f9fce6d5245cfa00168b760217d40
    apiBase: https://api.deepseek.com

defaultModel: DeepSeek